name: Bug report
description: Create a report to help us improve
assignees: neochief
body:
  - type: markdown
    attributes:
      value: |
        > [!NOTE]
        > If you have a general question, feedback, or an idea to share, please [start a 💬discussion](https://github.com/GitByBit-com/community/discussions/new/choose) instead of reporting a bug."

  - type: textarea
    id: body
    attributes:
      label: Bug report
      description: "How do you trigger this bug? Please walk us through it step by step."
     
    validations:
      required: true

  - type: input
    id: vs-code-version
    attributes:
      label: VSCode version (see in Main menu > About VS Code)

  - type: input
    id: operating-system
    attributes:
      label: Which operating systems have you used?

  - type: input
    id: git-version
    attributes:
      label: Git version (if related to git commands)
